variables:
  - name: mavenCacheFolder
    value: $(Pipeline.Workspace)/.m2/repository
  - name: mavenCacheOpts
    value: '-Dmaven.repo.local=$(mavenCacheFolder)'

stages:
  - stage: e2e
    pool: dv-dev-ubuntu2204
    jobs:
    - job: cypress
      steps:
      - checkout: self
        displayName: Set up repository
        submodules: recursive # needed for submodules
      - task: Cache@2
        inputs:
          # bump 'versionx' to make sure the cache is cleared
          key: 'version2 | maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(mavenCacheFolder)
        displayName: Cache Maven local repo
      - task: Maven@3
        displayName: Build project artifacts
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m $(mavenCacheOpts)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'clean install'
          options: ' -Pwar -Dmaven.artifact.threads=30 -Dwro4j-prebuild-cache '
      - task: Bash@3
        displayName: Set up liquibase properties
        inputs:
          workingDirectory: liquibase
          targetType: inline
          script: |
            cp liquibase.properties.example liquibase.properties
      - task: Bash@3
        displayName: Run cypress tests
        inputs:
          workingDirectory: vlaanderen/cypress-e2e
          targetType: inline
          script: |
            # echo "echoing liquibase dir"
            # ls ../../liquibase
            # echo "echoing target dir"
            # ls ../../web/target
            # /usr/libexec/docker/cli-plugins/docker-compose version
            # /usr/local/bin/docker-compose version
            # docker-compose version
            # echo ">>> build geonetwork"
            # /usr/libexec/docker/cli-plugins/docker-compose build geonetwork
            # echo ">>> listing images"
            # docker image ls | grep geonetwork
            # echo ">>> attempt 2"
            # docker --version
            # docker -D compose run --rm e2e
            # echo ">>> run e2e"
            # /usr/libexec/docker/cli-plugins/docker-compose run --rm e2e
            # echo ">>> liquibase logs"
            # # docker logs $(docker ps -aqf "name=cypress-e2e-liquibase-1")
            # # echo ">>> geonetwork logs"
            # docker logs $(docker ps -aqf "name=cypress-e2e-geonetwork-1")
            # echo ">>> inspect geonetwork"
            # docker inspect $(docker ps -aqf "name=cypress-e2e-geonetwork-1")
            # echo ">>> memory"
            # free -h
            # echo ">>> docker down"
            # /usr/libexec/docker/cli-plugins/docker-compose down -v
            # echo ">>> geonetwork logs"
            # /usr/libexec/docker/cli-plugins/docker-compose logs geonetwork
            # echo ">>> database logs"
            # /usr/libexec/docker/cli-plugins/docker-compose logs database
            # echo ">>> elasticsearch logs"
            # /usr/libexec/docker/cli-plugins/docker-compose logs elasticsearch
            # for some weird reason, just upping e2e doesn't work and geonetwork fails with unhealthy state
            # first get geonetwork 'warm', then launch e2e
            echo ">>> geonetwork reindexer"
            docker compose up -d --wait geonetwork-reindexer
            echo ">>> e2e"
            docker compose up e2e
            echo ">>> checking test results"
            find . -name "*.xml"
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
