trigger:
- develop

jobs:
- job: publish
  timeoutInMinutes: "60"
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    displayName: Set up repository
    submodules: recursive
  - task: Bash@3
    displayName: Set git sha as environment variable
    inputs:
      targetType: 'inline'
      script: |
        GIT_COMMIT_SHA=$(git rev-parse HEAD)
        echo "GIT_COMMIT_SHA: ${GIT_COMMIT_SHA}"
        echo "##vso[task.setvariable variable=GIT_COMMIT_SHA]${GIT_COMMIT_SHA}"
  - task: Maven@3
    displayName: Build project artifacts
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      options: ' -DskipTests -Pwar'
  - task: Docker@2
    displayName: Build web image and push to registry
    inputs:
      containerRegistry: 'joadevcontainerregistry'
      repository: 'metadata/geonetwork'
      command: 'buildAndPush'
      Dockerfile: 'web/Dockerfile'
      # $(GIT_COMMIT_SHA) -> add this tag when the container registry is configured with retention policies
      tags: |
        latest
        develop
  - task: Kubernetes@1
    displayName: Rolling update of Geonetwork
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'dvl-dev-infocat-ARM'
      azureResourceGroup: 'joa-dev-playground'
      kubernetesCluster: 'joa-dev-test-cluster'
      namespace: 'metadata'
      command: 'rollout'
      arguments: 'restart deployment/geonetwork'