trigger:
- develop

variables:
  - name: subscription
    value: METADATA-dev
  - name: clusterRg
    value: pre-md-cluster-rg
  - name: clusterName
    value: pre-md-cluster-aks
  - name: mavenCacheFolder
    value: $(Pipeline.Workspace)/.m2/repository
  - name: mavenCacheOpts
    value: '-Dmaven.repo.local=$(mavenCacheFolder)'

jobs:
- job: publish
  timeoutInMinutes: "60"
  # itss linux build server
  pool: dv-alex-adobuildserves-ubuntu-vmss
  steps:
    - checkout: self
      displayName: Set up repository
      submodules: recursive # needed for submodules
    - task: AzureCLI@2
      displayName: Configure access to aks cluster
      inputs:
        azureSubscription: 'dvl-dev-infocat-ARM'
        addSpnToEnvironment: true
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # download kubectl and kubelogin
          sudo az aks install-cli --subscription ${{ variables.subscription }} --client-version latest --kubelogin-version latest --only-show-errors

          # download ~/.kube/config file
          az aks get-credentials --resource-group ${{ variables.clusterRg }} --name ${{ variables.clusterName }} --only-show-errors

          # convert ~/.kube/config to a format compatible with kubelogin
          kubelogin convert-kubeconfig --login spn

          # create secure azure devops variables for later steps
          echo "##vso[task.setvariable variable=spnId;isSecret=true]$servicePrincipalId"
          echo "##vso[task.setvariable variable=spnSecret;isSecret=true]$servicePrincipalKey"
    - task: Bash@3
      displayName: Execute liquibase
      env:
        LIQUIBASE_GN_SYSTEM_FEEDBACK_MAILSERVER_PASSWORD: abc
        LIQUIBASE_MDV_PASSWORDHASH: abc
      inputs:
        targetType: 'inline'
        workingDirectory: 'liquibase'
        script: |
          ./execute-on-env.sh -n dev
