trigger:
- develop

jobs:
- job: publish
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Bash@3
    displayName: Set git sha as environment variable
    inputs:
      targetType: 'inline'
      script: |
        GIT_COMMIT_SHA=$(git rev-parse HEAD)
        echo "GIT_COMMIT_SHA: ${GIT_COMMIT_SHA}"
        echo "##vso[task.setvariable variable=GIT_COMMIT_SHA]${GIT_COMMIT_SHA}"
  - task: Maven@3
    displayName: Build project artifacts
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      options: ' -DskipTests -Pwar'
  - task: DockerCompose@0
    displayName: Build geonetwork image
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'dvl-dev-infocat-ARM'
      azureContainerRegistry: '{"loginServer":"joadevcontainerregistry.azurecr.io", "id" : "/subscriptions/8765c145-857e-40e9-a184-c69d80e2ba64/resourceGroups/joa-dev-playground/providers/Microsoft.ContainerRegistry/registries/joadevcontainerregistry"}'
      dockerComposeFile: 'docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'build'
      arguments: 'geonetwork'
      abortOnContainerExit: true
      additionalImageTags: |
        latest
        develop
        $(GIT_COMMIT_SHA)
  - task: Docker@2
    displayName: Push geonetwork image
    inputs:
      containerRegistry: 'joadevcontainerregistry'
      repository: 'metadata/geonetwork'
      command: 'push'
      tags: |
        latest
        develop
        $(GIT_COMMIT_SHA)