stages:
  # check whether we can/should skip this pipeline, e.g., for comment-only fixes
  - stage: skipcheck
    jobs:
      - job: skipcheck
        steps:
          - bash: |
              echo "Testing whether we need to skip the pipeline."
              substring='skipci'
              echo "> substring: $substring"
              echo "> commit message: $COMMIT_MESSAGE"
              if [[ "$COMMIT_MESSAGE" == *"$substring"* ]];
              then
                echo "> '$substring' was found in the commit message, skipping the pipeline."
                echo "##vso[task.setvariable variable=skip;isoutput=true]true"
              else
                echo "> '$substring' was not found in the commit message, proceeding with pipeline."
                echo "##vso[task.setvariable variable=skip;isoutput=true]false"
              fi
            name: skipcheck
            env:
              COMMIT_MESSAGE: $(Build.SourceVersionMessage)

