trigger:
- develop

jobs:
- job: publish
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Bash@3
    displayName: Set git sha as environment variable
    inputs:
      targetType: 'inline'
      script: |
        GIT_COMMIT_SHA=$(git rev-parse HEAD)
        echo "GIT_COMMIT_SHA: ${GIT_COMMIT_SHA}"
        echo "##vso[task.setvariable variable=GIT_COMMIT_SHA]${GIT_COMMIT_SHA}"
  - task: Maven@3
    displayName: Build project artifacts
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      options: ' -DskipTests -Pwar'
  - task: Docker@2
    displayName: Build web image and push to registry
    inputs:
      containerRegistry: 'joadevcontainerregistry'
      repository: 'metadata/geonetwork'
      command: 'buildAndPush'
      Dockerfile: 'web/Dockerfile'
      tags: |
        latest
        develop
        $(GIT_COMMIT_SHA)