# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

jobs:
- job: publish
  timeoutInMinutes: 60
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
      options: ' -DskipTests -Pwar'
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'dvl-dev-infocat-ARM'
      azureContainerRegistry: '{"loginServer":"joadevcontainerregistry.azurecr.io", "id" : "/subscriptions/8765c145-857e-40e9-a184-c69d80e2ba64/resourceGroups/joa-dev-playground/providers/Microsoft.ContainerRegistry/registries/joadevcontainerregistry"}'
      dockerComposeFile: 'docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'build'
      arguments: 'geonetwork'
      abortOnContainerExit: true
  - task: Docker@2
    inputs:
      containerRegistry: 'joadevcontainerregistry'
      repository: 'metadata/geonetwork'
      command: 'push'
      tags: |
        latest
        develop