# A default docker-compose override file. When specifying your own override file, this will not automatically be added.
services:
  database:
    ports:
      - "5432:5432"

  geonetwork:
    ports:
      - "8080:8080"

  elasticsearch:
    ports:
      - "9200:9200"