version: '3'
services:
  oidc_mock:
    image: qlik/simple-oidc-provider
    container_name: oidcmock.localhost.proxy
    ports:
      - "9000:80"
    environment:
      REDIRECTS: http://localhost:8080/geonetwork/login/oauth2/code/geonetwork-oicd
      CONFIG_FILE: /tmp/config/oidc-mock-config.json
      USERS_FILE: /tmp/config/oidc-mock-users.json
    volumes:
      - ./config:/tmp/config

  oidc_proxy:
    container_name: oicd_proxy
    image: shroomlife/docker-https-proxy:latest
    ports:
      - "80:80"
      - "443:443"
