specs:
  - name: schematron-rules-mdcat
    # level: sh:Violation
    title:
      dut: Metadata DCAT - Verplicht
      eng: Metadata DCAT - Mandatory
      fre: Metadata DCAT - Obligatoire
      ger: Metadata DCAT - Obligatorisch
    url: https://data.vlaanderen.be/doc/applicatieprofiel/metadata-dcat/erkendestandaard/2022-04-21/shacl/metadata-voor-services-ap-SHACL.ttl
    profile: https://data.vlaanderen.be/doc/applicatieprofiel/metadata-dcat

  - name: schematron-rules-mdcat-rec
    level: sh:Warning
    title:
      dut: Metadata DCAT - Aanbevolen
      eng: Metadata DCAT - Recommended
      fre: Metadata DCAT - Recommandé
      ger: Metadata DCAT - Empfohlen
    url: https://data.vlaanderen.be/doc/applicatieprofiel/metadata-dcat/erkendestandaard/2022-04-21/shacl/metadata-voor-services-ap-SHACL.ttl
    profile: https://data.vlaanderen.be/doc/applicatieprofiel/metadata-dcat

  # - name: schematron-rules-dcat-ap-vl
  #   level: sh:Violation
  #   title:
  #     dut: DCAT-AP-Vlaanderen - Verplicht
  #     eng: DCAT-AP-Vlaanderen - Mandatory
  #     fre: DCAT-AP-Vlaanderen - Obligatoire
  #     ger: DCAT-AP-Vlaanderen - Obligatorisch
  #   url: https://data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL/erkendestandaard/2026-02-12/shacl/DCAT-AP-VL-SHACL.ttl
  #   profile: https://data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL

  # - name: schematron-rules-dcat-ap-vl-rec
  #   level: sh:Warning
  #   title:
  #     dut: DCAT-AP-Vlaanderen - Aanbevolen
  #     eng: DCAT-AP-Vlaanderen - Recommended
  #     fre: DCAT-AP-Vlaanderen - Recommandé
  #     ger: DCAT-AP-Vlaanderen - Empfohlen
  #   url: https://data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL/erkendestandaard/2026-02-12/shacl/DCAT-AP-VL-SHACL.ttl
  #   profile: https://data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL

  - name: schematron-rules-mobility-110
    level: sh:Violation
    title:
      dut: Mobility (v1.1.0)
      eng: Mobility (v1.1.0)
      fre: Mobility (v1.1.0)
      ger: Mobility (v1.1.0)
    url: https://raw.githubusercontent.com/mobilityDCAT-AP/mobilityDCAT-AP/refs/heads/gh-pages/releases/1.1.0/shaclShapes/mobilitydcat-ap_shacl_shapes.ttl
    profile: https://w3id.org/mobilitydcat-ap/releases/1.1.0/

  - name: schematron-rules-mobility-110-rec
    level: sh:Warning
    title:
      dut: Mobility - Recommended (v1.1.0)
      eng: Mobility - Recommended (v1.1.0)
      fre: Mobility - Recommended (v1.1.0)
      ger: Mobility - Recommended (v1.1.0)
    url: https://raw.githubusercontent.com/mobilityDCAT-AP/mobilityDCAT-AP/refs/heads/gh-pages/releases/1.1.0/shaclShapes/mobilitydcat-ap_shacl_shapes.ttl
    profile: https://w3id.org/mobilitydcat-ap/releases/1.1.0/

  # - name: schematron-rules-dcat-ap
  #   level: sh:Warning
  #   title:
  #     dut: Aanbevolen DCAT-AP
  #     eng: Recommended DCAT-AP Rules
  #     fre: Recommended DCAT-AP Rules
  #     ger: Recommended DCAT-AP Rules
  #   url:
  #     - https://semiceu.github.io/DCAT-AP/releases/3.0.0/html/shacl/shapes_recommended.ttl
  #   profile: http://data.europa.eu/r5r#

