# scaled version of the override file
include:
  - docker-compose.yml
  - docker-compose.override.yml

services:
  geonetwork:
    profiles: [ "full", "scaled" ]
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "8080-8089:8080"

  geonetwork-harvester:
    profiles: [ "scaled" ]
    ports:
      - "8090:8080"
