# The default docker-compose override file. When specifying your own override file, this will not automatically be added.
# When just running `docker-compose up` it will use both docker-compose.yml and this file.

volumes:
  pgdata:
  pglog:
  esdata:
  geonetworkdata:

services:
  database:
    ports:
      - "5432:5432"

  geonetwork:
    profiles: [ "scaled" ]
    deploy:
      mode: replicated
      # you can pass the following to docker-compose to override the scale as well:
      # --scale geonetwork=2
      replicas: 1
    ports:
      - "8081-8089:8080"

  geonetwork-harvester:
    profiles: [ "full", "scaled" ]
    ports:
      - "8080:8080"

  geonetwork-reindexer:
    profiles: [ "full" ]

  elasticsearch:
    ports:
      - "9200:9200"

  ogc-api-records-service:
    # use the locally built image, assumes it was tagged correctly
    build: .
    image: localhost/gn-cloud-ogc-api-records-service:vl-1.0.1
    ports:
      - "8081:8080"
