# Check README.md for example usage.

volumes:
  pgdata:
  pglog:
  esdata:
  geonetworkdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/tmp/geonetwork/ha/data'

services:
  database:
    ports:
      - "5432:5432"

  geonetwork:
    environment:
      JAVA_OPTS: >
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.dir=/geonetwork-data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/root/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/root/WEB-INF/data/config/schema_plugins
        -Dgeonetwork.htmlcache.dir=/tmp/geonetwork/ha/htmlcache
    ports:
      - "8085-8090:8080"
    volumes:
      - geonetworkdata:/geonetwork-data

  elasticsearch:
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ogc-api-records-service:
    ports:
      - "8081:8080"
